# Generated by Django 4.1.4 on 2022-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='INN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CV',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='ISU',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hardskill_softskill',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
